version: '3.8'

services:
  db:
    image: postgres:14
    container_name: eduplatform_db
    environment:
      POSTGRES_DB: eduplatform_db
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: edu_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
