[tool.poetry]
name = "eduplatform"
version = "0.1.0"
description = ""
authors = ["igor treshchev <kontekst.seo@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
